
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umayanga Avi
 */
public class Student_Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Student_Register
     */
    public Student_Register_Form() {
        initComponents();
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(male_radio);
        bg.add(female_radio);
        
        table_view();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        male_radio = new javax.swing.JRadioButton();
        female_radio = new javax.swing.JRadioButton();
        ol_check = new javax.swing.JCheckBox();
        al_check = new javax.swing.JCheckBox();
        nvq_check = new javax.swing.JCheckBox();
        cource_combo = new javax.swing.JComboBox<>();
        reset_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        dob_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detail_tble = new javax.swing.JTable();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SLGTI Student Record");

        jLabel2.setText("Search");

        jLabel3.setText("Student ID");

        jLabel4.setText("Name");

        jLabel5.setText("Address");

        jLabel6.setText("Gender");

        jLabel7.setText("Qualification");

        jLabel8.setText("Course");

        jLabel9.setText("DOB");

        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_txtKeyReleased(evt);
            }
        });

        male_radio.setText("Male");

        female_radio.setText("Female");

        ol_check.setText("O/L");

        al_check.setText("A/L");

        nvq_check.setText("NVQ-4");

        cource_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "English" }));

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        detail_tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detail_tble);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(male_radio)
                                            .addComponent(ol_check))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(female_radio)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(al_check)
                                                .addGap(18, 18, 18)
                                                .addComponent(nvq_check))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dob_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cource_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(male_radio)
                            .addComponent(female_radio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ol_check)
                            .addComponent(al_check)
                            .addComponent(nvq_check))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cource_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(dob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reset_btn)
                            .addComponent(delete_btn)
                            .addComponent(update_btn)
                            .addComponent(save_btn))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        
        PreparedStatement ps;
        
        String id = id_txt.getText();
        String name = name_txt.getText();
        String address = address_txt.getText();
        String gender;
        if (male_radio.isSelected()) {
            gender="Male";
        }else if(female_radio.isSelected()){
            gender="Female";
        }else{
            gender = "No Selected";
        } 
        String qualification;
        if (ol_check.isSelected()) {
            qualification = "O/L";
        }else if (al_check.isSelected()) {
            qualification = "A/L";
        }else if (nvq_check.isSelected()) {
            qualification = "NVQ-4";
        }else{
            qualification = "Nothing Added..";
        }
        String course = (String) cource_combo.getSelectedItem();
        String dob = dob_txt.getText();
        
        
        String insert_query = "INSERT INTO `student`(`sid`, `name`, `address`, `gender`, `qualification`, `course`, `dob`) VALUES (?,?,?,?,?,?,?)";
        
        try {
            ps = My_Connection.getConnection().prepareStatement(insert_query);
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, address);
            ps.setString(4, gender);
            ps.setString(5, qualification);
            ps.setString(6, course);
            ps.setString(7, dob);
            
            ps.executeUpdate();
            table_view();
            JOptionPane.showMessageDialog(null, "Value is added...");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Student_Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_save_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        
        PreparedStatement ps;
        
        String id = id_txt.getText();
        String name = name_txt.getText();
        String address = address_txt.getText();
        String gender;
        if (male_radio.isSelected()) {
            gender="Male";
        }else if(female_radio.isSelected()){
            gender="Female";
        }else{
            gender = "No";
        } 
        String qualification;
        if (ol_check.isSelected()) {
            qualification = "O/L";
        }else if (al_check.isSelected()) {
            qualification = "A/L";
        }else if (nvq_check.isSelected()) {
            qualification = "NVQ-4";
        }else{
            qualification = "No";
        }
        String course = (String) cource_combo.getSelectedItem();
        String dob = dob_txt.getText();
        
        
        String update_query = "UPDATE `student` SET `sid`=?,`name`=?,`address`=?,`gender`=?,`qualification`=?,`course`=?,`dob`=? WHERE `sid`=?";
        
        try {
            ps = My_Connection.getConnection().prepareStatement(update_query);
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, address);
            ps.setString(4, gender);
            ps.setString(5, qualification);
            ps.setString(6, course);
            ps.setString(7, dob);
            
            ps.setString(8, id);
            ps.executeUpdate();
            table_view();
            JOptionPane.showMessageDialog(null, "Value is updated...");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Student_Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        
        PreparedStatement ps;
        
        String id = id_txt.getText();
        
        String delete_query = "DELETE FROM `student` WHERE `sid`=?";
        
        try {
            ps = My_Connection.getConnection().prepareStatement(delete_query);
            ps.setString(1, id);
            
            ps.executeUpdate();
            table_view();
            clearTextMethod();
            JOptionPane.showMessageDialog(null, "Value is deleted...");
            
        } catch (SQLException ex) {
            Logger.getLogger(Student_Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
       
        clearTextMethod();
        table_view();
        
    }//GEN-LAST:event_reset_btnActionPerformed

    private void search_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyReleased
       
        String text = search_txt.getText();
        String tx= "";
        if (text.equals(tx)) {
            clearTextMethod();
            table_view();
        } else {

            seachingMethod();
            search_tableMethod();
        }
        
        
    }//GEN-LAST:event_search_txtKeyReleased

    public void search_tableMethod(){

        PreparedStatement ps;
        ResultSet rs;
   
        try {
            
            String query ="SELECT * FROM `student` WHERE `sid`=?";
            ps = My_Connection.getConnection().prepareStatement(query);
            ps.setString(1, search_txt.getText());
            rs = ps.executeQuery();
            detail_tble.setModel(DbUtils.resultSetToTableModel(rs));
 
        } catch (Exception e) {
        }
}
    
    public void seachingMethod(){
    
        PreparedStatement ps;
        ResultSet rs;
  
        String male = "Male";
        String female = "Female";
        String ol = "O/L";
        String al = "A/L";
        String nvq = "NVQ-4";
        
        
        String searching_value = search_txt.getText();
   
        String search_query ="SELECT * FROM `student` WHERE `sid`=?";
        
        try {
            
            
            ps = My_Connection.getConnection().prepareStatement(search_query);
            ps.setString(1, searching_value);
            rs = ps.executeQuery();
  
            if (rs.next()) {
                 
                id_txt.setText(rs.getString("sid"));
                name_txt.setText(rs.getString("name"));
                address_txt.setText(rs.getString("address"));
                
                if (male.equals(rs.getString("gender"))) {
                    male_radio.setSelected(true);
                    female_radio.setSelected(false);
                }else if (female.equals(rs.getString("gender"))){
                    female_radio.setSelected(true);
                    male_radio.setSelected(false);
                }else if (!male.equals(rs.getString("gender")) || !female.equals(rs.getString("gender"))) {
                    female_radio.setSelected(false);
                    male_radio.setSelected(false);
                }
                
                cource_combo.setSelectedItem(rs.getString("course"));
                dob_txt.setText(rs.getString("dob"));
                
                if (ol.equals(rs.getString("qualification"))) {
                    ol_check.setSelected(true);
                    al_check.setSelected(false);
                    nvq_check.setSelected(false);
                }else if (al.equals(rs.getString("qualification"))) {
                    al_check.setSelected(true);
                    ol_check.setSelected(false);
                    nvq_check.setSelected(false);
                }else if (nvq.equals(rs.getString("qualification"))) {
                    nvq_check.setSelected(true);
                    ol_check.setSelected(false);
                    al_check.setSelected(false);
                }
                
            }

        } catch (Exception e) {
        }
}
    public void table_view(){

        PreparedStatement ps;
        ResultSet rs;

        String query ="SELECT * FROM `student`";

        try {
            ps = My_Connection.getConnection().prepareStatement(query);
            rs = ps.executeQuery();
            detail_tble.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            
        }
    }
    
    public void clearTextMethod(){
        
        search_txt.setText("");
        id_txt.setText("");
        name_txt.setText("");
        address_txt.setText("");
        male_radio.setSelected(false);
        female_radio.setSelected(false);
        ol_check.setSelected(false);
        al_check.setSelected(false);
        nvq_check.setSelected(false);
        cource_combo.setSelectedIndex(0);
        dob_txt.setText("");
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JCheckBox al_check;
    private javax.swing.JComboBox<String> cource_combo;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTable detail_tble;
    private javax.swing.JTextField dob_txt;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JTextField name_txt;
    private javax.swing.JCheckBox nvq_check;
    private javax.swing.JCheckBox ol_check;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
